//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18408
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceAuthentification")]
public interface ServiceAuthentification
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:ServiceAuthentification/DoWork", ReplyAction="urn:ServiceAuthentification/DoWorkResponse")]
    void DoWork();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:ServiceAuthentification/DoWork", ReplyAction="urn:ServiceAuthentification/DoWorkResponse")]
    System.Threading.Tasks.Task DoWorkAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:ServiceAuthentification/VerifierUser", ReplyAction="urn:ServiceAuthentification/VerifierUserResponse")]
    bool VerifierUser(string userentry, string passentry);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:ServiceAuthentification/VerifierUser", ReplyAction="urn:ServiceAuthentification/VerifierUserResponse")]
    System.Threading.Tasks.Task<bool> VerifierUserAsync(string userentry, string passentry);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ServiceAuthentificationChannel : ServiceAuthentification, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceAuthentificationClient : System.ServiceModel.ClientBase<ServiceAuthentification>, ServiceAuthentification
{
    
    public ServiceAuthentificationClient()
    {
    }
    
    public ServiceAuthentificationClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceAuthentificationClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceAuthentificationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceAuthentificationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void DoWork()
    {
        base.Channel.DoWork();
    }
    
    public System.Threading.Tasks.Task DoWorkAsync()
    {
        return base.Channel.DoWorkAsync();
    }
    
    public bool VerifierUser(string userentry, string passentry)
    {
        return base.Channel.VerifierUser(userentry, passentry);
    }
    
    public System.Threading.Tasks.Task<bool> VerifierUserAsync(string userentry, string passentry)
    {
        return base.Channel.VerifierUserAsync(userentry, passentry);
    }
}
